In [163]:
# worked on dataset loading, facing some bugs in displaying so will work on that
import torch
import torchvision
import torchvision.transforms as transforms
from torchvision.datasets import MNIST
import numpy as np


In [25]:
from torch.utils.data import DataLoader

In [24]:
import torch

print("PyTorch version:", torch.__version__)


PyTorch version: 2.0.1+cu117


In [9]:
import os
os.path.abspath('__file__')

'c:\\Users\\pande\\OneDrive\\Documents\\code\\ML\\ML-book-journey\\implementations\\__file__'

In [61]:
# Custom transformation to flatten the input tensor
class Flatten(object):
    def __call__(self, tensor):
        return tensor.view(-1)

In [86]:
root="../datasets/"
num_images=60000
image_dim=28*28

'''without flatten'''
transform=transforms.Compose([transforms.ToTensor(),])

'''with flatten, doesnt work properly'''
# transform=transforms.Compose([transforms.ToTensor(),transforms.Lambda(torch.flatten)])


# Create training dataset
train_dataset = MNIST(root=root+'MNIST_', train=True, download=True, transform=transform)

# Create DataLoader for training dataset
batch_size = 64
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)

channels=1
nimages = 0
mean = 0.0
var = 0.0
for i_batch, batch_target in enumerate(train_loader):
    # print("ibatch",i_batch)
    batch = batch_target[0]
    # print(batch.size(0),batch.size(1))

    # Rearrange batch to be the shape of [B, C, W * H]
    batch = batch.view(batch.size(0), batch.size(1), -1)
    # print(batch.size(0),batch.size(1))

    # Update total number of images
    nimages += batch.size(0)
    # Compute mean and std here
    mean += batch.mean(2).sum(0) 
    var += batch.var(2).sum(0)

    # print(mean)
    # print(var)
    # raise ZeroDivisionError

mean /= nimages
var /= nimages
std = torch.sqrt(var)

print("mean",mean)
print("mean",std)

tensor([0.1307])
tensor([0.3052])


In [117]:
root="../datasets/"
num_images=60000
image_dim=28*28

# '''without flatten'''
transform=transforms.Compose([transforms.ToTensor(),])

# transform=transforms.Compose([transforms.ToTensor(), transforms.Normalize((mean,),(std,))])

# Create training dataset
train_dataset = MNIST(root=root+'MNIST_', train=True, download=True, transform=transform)

# Create DataLoader for training dataset
batch_size = 64
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)


# Create training dataset
test_dataset = MNIST(root=root+'MNIST_', train=False, download=True, transform=transform)

# Create DataLoader for training dataset
batch_size = 64
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=True)

In [133]:
import torch

# Generate a random integer tensor in the range [0, 64) of shape (2, 3)
randint_tensor = torch.randint(low=0, high=64, size=(1,1))[0][0].item()
print(randint_tensor)


32


In [160]:
data_iter = iter(train_loader)
data, labels = next(data_iter)

# Accessing data from the batch
print("Data shape:", data.shape)
print("Labels shape:", labels.shape)

r=torch.randint(low=0, high=64, size=(1,1))[0][0].item()
# Example: Print the first image and its label from the batch
print("First image in the batch:")
print("img is ",r)
print(data[r])  # Accessing the first image

print("Label of the first image:", labels[0])  # Accessing the label of the first image

Data shape: torch.Size([64, 1, 28, 28])
Labels shape: torch.Size([64])
First image in the batch:
img is  35
tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.000

In [95]:
img = data[0][0]
m=28
for i in range(m):
    for j in range(m):
        val=[i][j]
        if (val>0):
            val="@"
        else:
            val="."
        print(val,end='')
    print()

.

IndexError: list index out of range

tensor([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [116]:
for batch_idx, (data, labels) in enumerate(train_loader):
    # data: tensor of shape (batch_size, channels, height, width)
    # labels: tensor of shape (batch_size)
    batch_idx=5
    # Accessing data from the current batch
    print("Batch Index:", batch_idx)
    print("Data shape:", data.shape)
    print("Labels shape:", labels.shape)

    # Example: Print the first image and its label from the batch
    print("First image in the batch:")
    print(data[0])  # Accessing the first image
    print("Label of the first image:", labels[0])  # Accessing the label of the first image

    # Accessing multiple images and labels from the batch
    for i in range(5):  # Accessing the first 5 images in the batch
        image = data[i]
        label = labels[i]
        # Process the image and label as needed

    break

Batch Index: 5
Data shape: torch.Size([64, 1, 28, 28])
Labels shape: torch.Size([64])
First image in the batch:
tensor([[[-0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281,
          -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281,
          -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281,
          -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281],
         [-0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281,
          -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281,
          -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281,
          -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281],
         [-0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281,
          -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281,
          -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281,
          -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281, -0.4281],
         