In [79]:
import torch as t
# from t import tensor
print(t.__version__)
# t1=t.tensor(2)

2.0.1+cu117


In [83]:
s=t.tensor(4)
s.ndim
s.item(), type(s.item())

(4, int)

In [89]:
# vector
a=t.tensor([3,3])
a, a.ndim #dimensions = number of square brackets

(tensor([3, 3]), 1)

In [96]:
# Matrix
L=[[1,2],[3,3]]
A=t.tensor([[1,2],[3,3]])
A
A.ndim
A[1]
A.shape

torch.Size([2, 2])

In [100]:
# Tensor
T=t.tensor([L,L])
T
T.ndim
T[0]

tensor([[1, 2],
        [3, 3]])

In [118]:
r=t.rand((224,224,3))
r.shape

torch.Size([224, 224, 3])

In [120]:
a=t.arange(1,100,23)
a
a=t.

tensor([ 1, 24, 47, 70, 93])

In [36]:
t1=tensor([[1,2,4]])
t1
t1.shape
# t1.item()

torch.Size([1, 3])

In [37]:
l=[1,3,4]
t3=t.as_tensor(l)
t3[0]=12
l, t3

([1, 3, 4], tensor([12,  3,  4]))

In [39]:
t1=t.as_tensor(t3)
t2=tensor(t3)
t1 is t3, t2 is t3

C:\Users\pande\AppData\Local\Temp\ipykernel_24460\1465824772.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t2=tensor(t3)


(True, False)

In [40]:
def copy(t3):
    '''
    returns deep copy of tensor, with gradients detached
    
    clone : clones the tensor , i.e. updations to new tensor arent reflected in old tensor

    detach : detaches the gradients of new tensor from old tensor
    '''
    return t3.clone().detach()

t2=copy(t3)

In [66]:
t3=t.zeros(4,5)
t4= t.ones_like(t3)
t4=t.eye(4)
t3, t4

t5= t.arange(1,5,0.5)
# t6= t.range(1,5,0.5) #depreciated
t5, t6

t7=t.empty(3,4)
t7=t.full((3,4),-2)

t7

tensor([[-2, -2, -2, -2],
        [-2, -2, -2, -2],
        [-2, -2, -2, -2]])

In [69]:
x=t.arange(8)
t.tensor_split(x,3), t.chunk(x,3)

((tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7])),
 (tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7])))

In [73]:
val=t.tensor([[100,200],[300,400]])
pos=t.tensor([[0,0],[1,0]])
t.gather(val,1,pos), t.gather(val,0,pos) #axis applies to pos, not val


(tensor([[100, 100],
         [400, 300]]),
 tensor([[100, 200],
         [300, 200]]))

In [77]:
a=t.arange(10)
a.reshape(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])